### ISSUE TITLE
Upload data to the Hugging Face Hub

### ISSUE THREAD

**Issue by davanstrien** [yeyimilk/LLM-Vision-Marine-Animals#1]
Very nice dataset/paper! It would be great to have the data on the Hugging Face Hub for better visibility/discoverability. I've uploaded a version here: https://huggingface.co/datasets/davanstrien/LLM-Vision-Marine-Animals. I would be happy to transfer to your org if you let me know your Hugging Face username.

**Comment by yeyimilk** [comment]
Hi @davanstrien, thanks for uploading the dataset to HF. My username is `yeyimilk`.
FYI, we have another project `https://github.com/yeyimilk/LLMGeo` which is about using LLM to guess the geolocation for images.

**Comment by davanstrien** [comment]
@yeyimilk sorry for slow reply! I've just moved the repo to here: https://huggingface.co/datasets/yeyimilk/LLM-Vision-Marine-Animals :) 

> FYI, we have another project https://github.com/yeyimilk/LLMGeo which is about using LLM to guess the geolocation for images.

Would be great to also have this on the Hub! Let me know if you need help with it.
